### PR TITLE
Show traffic driver suggestions

### PR DESCRIPTION
**Pull request by kelvin-chappell**
Eg.
image

Buttons have no effect until linking code in #62 is deployed.

/cc @guardian/labs-beta

### CODE REVIEW

**Review by steppenwells — CHANGES_REQUESTED** [review]
Would it be possible to wire up the buttons to real functionality before we roll this out?

Also how is ignore suggestion going to work?

**Comment by kelvin-chappell** [comment]
Yes, I'll keep this on hold until the linking is actually working.

I haven't worked out what to do with the ignore yet! Store it in dynamo I should think.

**Comment by kelvin-chappell** [comment]
The 'accept suggestion' functionality is now working!

(I'll get the 'ignore suggestion' working in a separate PR.)

**Comment by kelvin-chappell** [comment]
@steppenwells @clloyd Do you mind having a look over commit 0a23aef0a82d0f1506de9f72d3014d670d6bea8f please?

**Review by steppenwells — APPROVED** [review]
looks legit

**Pull request merged**
